Movie details screenShots preview
Hanzala-Github/Movie pull request #5
Opened 2024-07-30 07:52 UTC by Hanzala-Github

2024-07-30 14:44 UTC, SaadWorks247 requested changes

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
>    const movieImg = singleMovieQuery.data?.data?.movie.medium_cover_image;
Create a new const with value of singleMovieQuery?.data?.data?.movie and use that instead writting that every single time.

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
> +  // console.log();
Remove this comment

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
> +  console.log(genres);
Remove all console logs

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
> +      <div className="backgroundImage" style={containerStyle}></div>
change classname to background_image

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
> -        {/* Real */}
Remove all commented out and unused code

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
>          {DownloadPopup ? (
Remove ternary operator, instead use Boolean(downloadPopup) && <></>
Also use camelCase for variable/const names

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
>            <Link to="" style={{ textDecoration: "none" }}>
Use global css for this

2024-07-30 14:44 UTC, RehmanWorks247 commented on src/components/SingleMovie/SingleMovie.jsx
> +                <FiDownload style={{ fontSize: "20px", color: "#e7e7e7" }} />
Use Css for this

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/SingleMovie.jsx
> +            target="_"
change this to _blank

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/SingleMovie.jsx
> +            style={{ textDecoration: "none" }}
Remove this use global css class

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/SingleMovie.jsx
> +                  src="https://yts.mx/assets/images/website/logo-imdb.svg"
Download this image and put it in assets folder, Import that and use it

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/SingleMovieTrailer.jsx
> +  console.log();
Remove all console.logs from code

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/SummeryCast.jsx
> +  const summery = singleMoviedata.data?.data?.movie?.description_full;
create a reusable variable for this

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/TrailerImg.jsx
> +  const image1 = singleMoviedata.data?.data?.movie?.large_screenshot_image1;
use reusable variable for this

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/TrailerPhoto.jsx
> +  const image1 = singleMovieData.data?.data?.movie.large_screenshot_image1;
use Reusable variable for this

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/TrailerPhoto.jsx
> +  const singleMovieData = useGetSingleMoviesQuery(id);
pass data from props instead of refetching again

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/TrailerImg.jsx
> +          src={images[currentImageIndex]}
Pass this image from above instead of choosing between all of them

2024-07-30 14:44 UTC, Rehmankk360 commented on src/components/SingleMovie/TrailerPhoto.jsx
> +    setcurrentIndex((prev) => (prev - 1 + images.length) % images.length);
refer to above comment

2024-08-01 11:53 UTC, Hanzala-Github commented on src/components/SingleMovie/TrailerImg.jsx
> +  const image1 = singleMoviedata.data?.data?.movie?.large_screenshot_image1;
Fix this code i'll create the single variable

2024-08-01 11:55 UTC, Hanzala-Github commented on src/components/SingleMovie/TrailerPhoto.jsx
> +  const image1 = singleMovieData.data?.data?.movie.large_screenshot_image1;
Fix this code

2024-08-01 12:05 UTC, Hanzala-Github commented on src/components/SingleMovie/TrailerPhoto.jsx
> +  const singleMovieData = useGetSingleMoviesQuery(id);
Fix this with the help of this setTrailerPhoto i will render the Trailer img component

2024-08-01 12:12 UTC, Hanzala-Github commented on src/components/SingleMovie/TrailerImg.jsx
> +          src={images[currentImageIndex]}
Sorry i will not understand your comment please clear me you commint

2024-08-01 12:16 UTC, Hanzala-Github commented on src/components/SingleMovie/TrailerPhoto.jsx
> +    setcurrentIndex((prev) => (prev - 1 + images.length) % images.length);
i will put the comment on above this functions

2024-08-01 12:17 UTC, Hanzala-Github commented on src/components/SingleMovie/SingleMovie.jsx
>    const movieImg = singleMovieQuery.data?.data?.movie.medium_cover_image;
Fix this code cerate the new variable

2024-08-01 12:17 UTC, Hanzala-Github commented on src/components/SingleMovie/SingleMovie.jsx
> +  // console.log();
remove the all commint

2024-08-01 12:19 UTC, Hanzala-Github commented on src/components/SingleMovie/SingleMovie.jsx
> +  console.log(genres);
fix this code

2024-08-01 12:20 UTC, Hanzala-Github commented on src/components/SingleMovie/SingleMovie.jsx
> +      <div className="backgroundImage" style={containerStyle}></div>
i will change the class name

2024-08-01 12:21 UTC, Hanzala-Github commented on src/components/SingleMovie/SingleMovie.jsx
> -        {/* Real */}
i will put it null with this all empty strings

2024-08-01 14:49 UTC, closed without merging